import './components/burger.js'
import './components/dialog.js'
import './components/product-tabs.js'
import './components/product-detail-navigation.js'
import './components/fact-counter.js'
import './components/telegram-subscribe.js'
import './components/timer.js'
// import './components/img-loading-error.js'
// import './components/product-gallery.js'
